Financial-Times/n-header-footer

bower.json, main.scss, src/scss/header/_primary-tools.scss, templates/partials/primary-tools.html
=> Hide the 'my account' link at mobile

src/js/typeahead.js
@i-like-robots @matthew-andrews
=> moving typeahead onto ids

src/js/search.js, src/js/typeahead.js
=> moving even ore over to using concept ids for typeahead

templates/partials/primary-nav.html
/cc @i-like-robots @tom-parker
=> Add primary-nav hook for accessibility skip link

bower.json, src/js/notified.js
@adgad 
Depends on https://github.com/Financial-Times/next-ilyushin/pull/224
=> pointing myft link at a personalised page

templates/header.html
=> Make compatible with o-grid 3.2

src/scss/_vars_mixins.scss, src/scss/header/_masthead.scss, src/scss/header/_primary-tools.scss, templates/header.html, templates/partials/myft-tools.html, templates/partials/primary-tools.html
=> More masthead work

src/scss/header/_masthead.scss
=> Fix the account tools alignment with o-grid 3.x

src/scss/header/_navigation.scss, src/scss/header/_primary-tools.scss
Only a minor change in breakpoints.
See #40
=> Responsive behaviour of primary tools (fix #40)

src/scss/header-v2/_navigation.scss, src/scss/header/_masthead.scss, src/scss/header/_primary-tools.scss, templates/headerv2.html, templates/partials/navigation/all-templatev2.html, templates/partials/primary-tools.html
Fixes and design feedback - nav v2
fixes https://github.com/Financial-Times/next-front-page/issues/240
fixes https://github.com/Financial-Times/next-front-page/issues/237
fixes https://github.com/Financial-Times/next-front-page/issues/239
=> Design updates

src/js/search.js, src/js/typeahead.js, src/scss/header-v2/_search.scss, templates/headerv2.html, templates/partials/search-form.html, templates/partials/search-formv2.html
... by moving the typeahead suggestions to a different place for V2
Fix #53
=> Fix overflow issues properly

main.js, src/js/navigation.js, src/js/search.js, src/js/typeahead.js, src/scss/header-v2/_navigation.scss, src/scss/header-v2/_search.scss, templates/partials/navigation/all-templatev2.html, templates/partials/primary-tools.html, templates/partials/search-formv2.html
=> [Ready] Various issue fixes

templates/header.html
See [o-grid v4 upgrade notes](https://github.com/Financial-Times/o-grid/blob/v4/README.md#markupsass-changes)
=> Add container for o-grid v4 upgrade

demos/data.js, demos/main.js, gulpfile.js, main.js, package.json, src/js/is-outside.js, src/js/navigation.js, src/js/search.js, src/js/sticky.js, src/js/sub-nav.js, src/js/typeahead.js, src/scss/header-v2/_navigation.scss, src/scss/header-v2/_search.scss, src/scss/header/_base.scss, src/scss/header/_masthead.scss, templates/headerv2.html, templates/partials/navigation/all-templatev2.html, templates/partials/navigation/nav-template.html, templates/partials/primary-navv2.html
This pulls in the new IA from next-navigation, and also make a couple other visual tweaks to the navigation UI itself.
**requires next-express 14.2.2 or later**
/cc @ironsidevsquincy @i-like-robots
=> New information architecture

src/scss/_vars_mixins.scss, src/scss/header-v2/_navigation.scss, src/scss/header/_base.scss, src/scss/header/_masthead.scss, templates/headerv2.html
Fixes https://github.com/Financial-Times/n-header-footer/issues/80
=> Fix o-grid v4 markup

Makefile, circle.yml, package.json, src/scss/header-v2/_navigation.scss, src/scss/header/_masthead.scss, src/scss/header/_primary-tools.scss
All apps have switched over to v4
=> Remove o-gird v3 related tweaks

bower.json
(No actual breaking changes, and no visual changes)
=> Bump o-forms and o-expander

bower.json, src/js/typeahead.js
=> dom-delegate -> ftdomdelegate

templates/header.html
See https://github.com/Financial-Times/n-layout/pull/14
=> Ability to pass in html snippet to add before header

templates/partials/primary-navv2.html
=> Add: Input (type: checkbox) data trackable

templates/partials/search-formv2.html
By adding data-trackable to search to re-enable interaction, before fixing n-instrumentation.
/cc @ironsidevsquincy
=> Fix Navigation

src/scss/footer/_main.scss, templates/footer.html
=> Footer changes

src/scss/header-v2/_navigation.scss, src/scss/header/_primary-tools.scss
Also, underline 'menu' toggle on hover/focus
=> Border between primary tools

templates/partials/membership-tools.html
@ironsidevsquincy 
To keep consistency with other links (Sign Out / My Account)
=> Amend: Sign In link changed to sentence case

src/scss/header-v2/_navigation.scss
Fixes Financial-Times/next-front-page#327
=> Offset menu if markets data is displayed

src/scss/_vars_mixins.scss, src/scss/header/_masthead.scss, src/scss/header/_primary-tools.scss
cc @ironsidevsquincy 
Fixes https://github.com/Financial-Times/n-header-footer/issues/106
=> Change: Masthead links color to white

src/scss/header/_navigation.scss
cc @ironsidevsquincy 
Fixes https://github.com/Financial-Times/n-header-footer/issues/123
=> Fix: Menu alignment

src/scss/header/_navigation.scss
*Seems* to still work as expected
=> Remove menu delay

templates/partials/primary-nav.html
depends on https://github.com/Financial-Times/next-express/pull/274
=> Use standard nav items

templates/partials/myft-tools.html
=> Italicize the "my" in myFT

src/scss/header/_navigation.scss
cc @ironsidevsquincy @adgad 
Fixes https://github.com/Financial-Times/n-header-footer/issues/128
Fixes https://github.com/Financial-Times/n-navigation/issues/66
=> Remove: Link behaviour for Menu sub-level-header (exc. smallest breakpoint)

templates/partials/all.html
=> Move: Subnav topic data-trackable attribute from span to parent button

templates/header.html
@robin-marr-ft @andrewgeorgiou1981 @VladDubrovskis
=> Ads 598 - Moving ads styling from next apps to next-ads-component

main.scss, src/scss/header/_membership-mobile-promotion.scss, templates/header.html, templates/partials/membership-mobile-promotion.html
I've kept it a little bit separate to the header as it's going to evolve from this.
=> Add sign-in and subscribe links to mobile view

src/scss/header/_logo.scss, src/scss/header/_masthead.scss, src/scss/header/_search.scss, templates/footer.html
Also
* remove ALPHA
* placeholder text in footer search
=> Width of search icon, take two

src/scss/header/_navigation.scss, templates/partials/all.html
=> Edition switcher in mobile menu redux

src/scss/header/_membership-mobile-promotion.scss
=> up the z-index to hide under navigation

bower.json, src/js/edition-switcher.js
(Vanilla pages don't have the header)
=> Protection for pages using the vanilla template
